# Generated by Django 3.0.4 on 2020-05-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlw_survey', '0004_auto_20200515_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveycomment',
            old_name='author',
            new_name='owner',
        ),
    ]
